yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('django.contrib.auth.urls'))

]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(CreatedModel):
    text = models.TextField()
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ['-pub_date']


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name='Комментарий',
        on_delete=models.CASCADE,
        null=True,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):

    user = models.ForeignKey(
        User,
        verbose_name='Подписчик',
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'author'],
                                    name='unique_user_author')
        ]

yatube/posts/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import Comment, Post

User = get_user_model()


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('group', 'text', 'image')
        labels = {
            'text': 'Текст',
            'group': 'Группа',
        }
        help_texts = {
            'text': 'Текст поста',
            'group': 'Группа, к которой принадлежит пост',
        }

    def clean_text(self):
        data = self.cleaned_data['text']
        if data == "":
            raise forms.ValidationError('Нельзя создать пост с пустым полем')
        return data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст',
        }
        help_texts = {
            'text': 'Текст нового комментария',
        }

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post

User = get_user_model()

posts_per_page = 10


def index(request):
    post_list = Post.objects.select_related('author', 'group').all()
    paginator = Paginator(post_list, posts_per_page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = Post.objects.filter(group=group)
    paginator = Paginator(post_list, posts_per_page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'group': group,
        'page_obj': page_obj
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    total_posts = author.posts.all().count()
    post_list = author.posts.all()
    paginator = Paginator(post_list, posts_per_page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    following = (request.user.is_authenticated and author.following.filter(
        user=request.user).exists())

    context = {
        'author': author,
        'page_obj': page_obj,
        'total_posts': total_posts,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST)
    comments = post.comments.all()

    context = {
        'post': post,
        'form': form,
        'comments': comments,

    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            commit = form.save(commit=False)
            commit.author = request.user
            commit.save()
            return redirect('posts:profile', request.user.username)
        return render(request, 'posts/create_post.html', {'form': form})
    form = PostForm()
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:post_detail', post_id)
    return render(request, 'posts/create_post.html',
                  {"form": form, "post": post, "is_edit": True, })


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(posts_list, posts_per_page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    if user == author:
        return redirect('posts:profile', username=username)
    Follow.objects.get_or_create(user=user, author=author)

    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    is_follower = Follow.objects.filter(user=user, author=author)
    is_follower.delete()
    return redirect('posts:profile', username=author)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
    {% if is_edit %}
        Редактировать пост
    {% else %}
        Новый пост
    {% endif %}
{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}
    <main>
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-md-8 p-5">
                    <div class="card">
                        <div class="card-header">
                            {% if is_edit %}
                                Редактировать пост
                            {% else %}
                                Новый пост
                            {% endif %}
                        </div>
                        <div class="card-body">
                            {% load user_filters %} {# Загружаем фильтры #}
                            {% if form.errors %}
                                {% for field in form %}
                                    {% for error in field.errors %}
                                        <div class="alert alert-danger">
                                            {{ error|escape }}
                                        </div>
                                    {% endfor %}
                                {% endfor %}
                                {% for error in form.non_field_errors %}
                                    <div class="alert alert-danger">
                                        {{ error|escape }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                            {% if is_edit %}
                                <form method="post" enctype="multipart/form-data"
                                      action="{% url 'posts:post_edit' post.id %} ">
                            {% else %}
                                <form method="post" enctype="multipart/form-data"
                                      action="{% url 'posts:post_create' %}">
                            {% endif %}
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group row my-3">
                                    <label for="{{ field.id_for_label }}">
                                        {{ field.label }}
                                        {% if field.field.required %}
                                            <span class="required text-danger">*</span>
                                        {% endif %}
                                    </label>
                                    {# К полю ввода добавляем атрибут class #}
                                    {{ field|addclass:'form-control' }}
                                    {% if field.help_text %}
                                        <small
                                                id="{{ field.id_for_label }}-help"
                                                class="form-text text-muted"
                                        >
                                            {{ field.help_text|safe }}
                                        </small>
                                    {% endif %}
                                </div>
                            {% endfor %}
                            <button type="submit" class="btn btn-primary">
                                {% if is_edit %}
                                    Cохранить
                                {% else %}
                                    Добавить
                                {% endif %}
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% load thumbnail %}
{% load cache %}
{% block title %}
    Страница избранных постов
{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}
    {% include 'posts/includes/switcher.html' with follow=True %}
    {% cache 20 index_page %}
        <main>
            <div class="container py-5">
                <h1>Последние обновления на сайте </h1>
                {% for post in page_obj %}
                    <article>
                        <ul>
                            <li>
                                Автор: {{ post.author.get_full_name }}
                            </li>
                            <li>
                                Дата публикации: {{ post.pub_date|date:"d E Y" }}
                            </li>
                        </ul>
                        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                            <img alt="" class="card-img my-2" src="{{ im.url }}">
                        {% endthumbnail %}
                        <p>
                            {{ post.text }}
                        </p>
                        <a href="">все записи группы</a>
                        {% if not forloop.last %}
                            <hr>{% endif %}

                    </article>

                {% endfor %}

                {% include 'includes/paginator.html' %}

            </div>
        </main>
    {% endcache %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}
    {{ group.slug }}
{% endblock %}
{% block header %}{{ group }}{% endblock %}
{% block content %}
    <h1>{{ group.title }}</h1>
    <p>
        {{ group.description }}
    </p>
    {% for post in page_obj %}
        <article>
            <ul>
                <li>
                    Автор: {{ post.author.get_full_name }}
                </li>
                <li>
                    Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
            </ul>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img alt="" class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p>
                {{ post.text }}
            </p>
        </article>
        {% if not forloop.last %}
            <hr>{% endif %}
    {% endfor %}

    {% include 'includes/paginator.html' %}

    <!-- под последним постом нет линии -->
{% endblock content %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% load thumbnail %}
{% load cache %}
{% block title %}
    Главная страница
{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}
    {% include 'posts/includes/switcher.html' with index=True %}
    {% cache 20 index_page %}
        <main>
            <!-- класс py-5 создает отступы сверху и снизу блока -->
            <div class="container py-5">
                <h1>Последние обновления на сайте </h1>
                {% for post in page_obj %}
                    <article>
                        <ul>
                            <li>
                                Автор: {{ post.author.get_full_name }}
                            </li>
                            <li>
                                Дата публикации: {{ post.pub_date|date:"d E Y" }}
                            </li>
                        </ul>
                        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                            <img alt="" class="card-img my-2" src="{{ im.url }}">
                        {% endthumbnail %}
                        <p>
                            {{ post.text }}
                        </p>
                        <a href="">все записи группы</a>
                        {% if not forloop.last %}
                            <hr>{% endif %}

                    </article>

                {% endfor %}

                {% include 'includes/paginator.html' %}

            </div>
        </main>
    {% endcache %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% load user_filters %}
{% block title %}
    {{ post.text|truncatechars:30 }}
{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}
    <main>
        <div class="row">
            <aside class="col-12 col-md-3">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        Дата публикации: {{ post.pub_date|date:"d E Y" }}
                    </li>
                    <li class="list-group-item">
                        Группа: {{ post.text }}
                        <a href="">
                            все записи группы
                        </a>
                    </li>
                    <li class="list-group-item">
                        Автор: {{ post.author.get_full_name }}
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Всего постов автора: <span>{{ post.author.posts.count }}</span>
                    </li>
                    <li class="list-group-item">
                        <a href="">
                            все посты пользователя
                        </a>
                    </li>
                </ul>
            </aside>
            <article class="col-12 col-md-9">
                {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                    <img alt="" class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}
                <p>
                    {{ post.text }}
                </p>
                {% if post.author == request.user %}
                    <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
                        редактировать запись
                    </a>
                    {% if user.is_authenticated %}
                        <div class="card my-4">
                            <h5 class="card-header">Добавить комментарий:</h5>
                            <div class="card-body">
                                <form method="post" action="{% url 'posts:add_comment' post.id %}">
                                    {% csrf_token %}
                                    <div class="form-group mb-2">
                                        {{ form.text|addclass:"form-control" }}
                                    </div>
                                    <button type="submit" class="btn btn-primary">Отправить</button>
                                </form>
                            </div>
                        </div>
                    {% endif %}

                    {% for comment in comments %}
                        <div class="media mb-4">
                            <div class="media-body">
                                <h5 class="mt-0">
                                    <a href="{% url 'posts:profile' comment.author.username %}">
                                        {{ comment.author.username }}
                                    </a>
                                </h5>
                                <p>
                                    {{ comment.text }}
                                </p>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </article>
        </div>
    </main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}
    Профайл пользователя {{ author.get_full_name }}
{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}
    <main>
        <div class="container py-5">
            <div class="mb-5">
                <h1>Все посты пользователя {{ author.get_full_name }}</h1>
                <h3>Всего постов: {{ posts_count }}</h3>
                {% if following %}
                    <a
                            class="btn btn-lg btn-light"
                            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
                    >
                        Отписаться
                    </a>
                {% else %}
                    <a
                            class="btn btn-lg btn-primary"
                            href="{% url 'posts:profile_follow' author.username %}" role="button"
                    >
                        Подписаться
                    </a>
                {% endif %}
            </div>
            {% for post in page_obj %}
                <article>
                    <ul>
                        <li>
                            Автор: {{ post.author.get_full_name }}
                            <a href="">все посты пользователя</a>
                        </li>
                        <li>
                            Дата публикации: {{ post.pub_date|date:"d E Y" }}
                            <!--  Дата публикации: 31 июля 1854 -->
                        </li>
                    </ul>
                    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                        <img alt="" class="card-img my-2" src="{{ im.url }}">
                    {% endthumbnail %}
                    <p>
                        {{ post.text }}
                    </p>
                    <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
                </article>
                <a href="">все записи группы</a>
                {% if not forloop.last %}
                    <hr>{% endif %}
            {% endfor %}
            {% include 'includes/paginator.html' %}
        </div>
    </main>
{% endblock %}